language: node_js
sudo: false
node_js: stable
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
  - npm install -g bower polylint web-component-tester
  - bower install
  - polylint
script:
  - xvfb-run wct
env:
  - CXX=g++-4.8
